# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/home-assistant/base-python/aarch64:16.0.1"
  amd64: "ghcr.io/home-assistant/base-python/amd64:16.0.1"
  armhf: "ghcr.io/home-assistant/base-python/armhf:16.0.1"
  armv7: "ghcr.io/home-assistant/base-python/armv7:16.0.1"
  i386: "ghcr.io/home-assistant/base-python/i386:16.0.1"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Example add-on"
  org.opencontainers.image.description: "Example add-on to use as a blueprint for new add-ons."
  org.opencontainers.image.source: "https://github.com/home-assistant/addons-example"
  org.opencontainers.image.licenses: "Apache License 2.0"
# args:
#   TEMPIO_VERSION: "2021.09.0"
